PROJECTION = {
    "_id": 0,
    "a_enfant": 1,
    "age_begin": 1,
    "age_end": 1,
    "alcool": 1,
    "fumes": 1,
    "id_localisation": 1,
    "id_nvetudes": 1,
    "id_origine": 1,
    "id_physique": 1,
    "id_profession": 1,
    "id_statutmarital": 1,
    "id_utilisateur": 1,
    "is_converti": 1,
    "is_sync": 1,
    "last_modification": 1,
    "pratiquant": 1,
    "salat_pratique": 1,
    "taille_begin": 1,
    "taille_end": 1,
    "v_enfant": 1,
    "veil": 1,
    "wedding_project": 1,
}
